# Setup
title: Zeqiong Tan
description: M.Eng. student in Information Engineering, Southeast University
url: https://zqtann.github.io
avatar: /profile.png
paginate: 5
permalink: pretty
cover_image: /bg.png

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
# twitter:
#   username: zqtan
#   card: summary
logo: logo.png
social:
  name: Zeqiong Tan
  links:
    # - https://twitter.com/vszhub
    - https://scholar.google.com/citations?hl=zh-CN&user=lcd2aEQAAAAJ
    - https://github.com/vszhub
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Zeqiong Tan
  url: https://github.com/zqtann/
  email: zqtan@seu.edu.cn
